# Generated by Django 4.2.11 on 2025-08-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_watchlist_delete_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.auctionlisting'),
        ),
    ]
