# Generated by Django 4.2.11 on 2025-08-07 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auctionlisting_auction_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='auction_listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.auctionlisting'),
        ),
    ]
